[project]
name = "brain"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Tanseer Saji", email = "tanseersaji@gmail.com" }
]
requires-python = ">=3.14"
dependencies = [
    "matplotlib>=3.11.2",
    "numpy>=2.5.3",
    "tensorboard>=2.21.0",
    "torch>=2.14.0",
]

[project.scripts]
brain = "brain:main"

[build-system]
requires = ["uv_build>=0.12.13,<0.13.0"]
build-backend = "uv_build"
